spring.application.name=campus-navigator
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/campus_graph
spring.datasource.username=campus_user
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgresPlusDialect
