spring.application.name=campus-navigator
server.port=${PORT:8090}

<<<<<<< HEAD
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/campus_graph}
spring.datasource.username=${DB_USER:campus_user}
=======
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/campus_navigator}
spring.datasource.username=${DB_USER:campus_navigator_user}
>>>>>>> 0fa69f67ad0e3c26bfb214cf9d0b350ba7692aa7
spring.datasource.password=${DB_PASS:123456789}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

app.frontend.url=${FRONTEND_URL:http://localhost:5173/}

jwt.secret=${JWT_SECRET:dtyfukglufidtyckvjhyufikvhjfuyokvhj}
jwt.expiration=${JWT_EXPIRATION:86400000}

admin.username=${ADMIN_USERNAME:campus_admin}
admin.password=${ADMIN_PASSWORD:123456789}